package:
  name: "brainio"
  version: "0.2"

source:
  path: .

build:
  number: 0
  noarch: generic
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - six
    - boto3
    - tqdm
    - Pillow
    - entrypoints
    - pytz>=2020.1
    - numpy>=1.16.5, !=1.21.*
    - pandas>=1.2.0, !=1.3.0
    - xarray==0.17.0
    - netcdf4

  run:
    - python
    - six
    - boto3
    - tqdm
    - Pillow
    - entrypoints
    - pytz>=2020.1
    - numpy>=1.16.5, !=1.21.*
    - pandas>=1.2.0, !=1.3.0
    - xarray==0.17.0
    - netcdf4

about:
  home: "https://github.com/brain-score/brainio"
  